version: '3.8'
services:
    laravel:
        image: bitnami/laravel:latest
        ports:
            - "8000:8000"
        env_file:
            - ./.env
        volumes:
            - ./:/app
        depends_on:
            - mysql
        command : ["sh", "-c", "composer install && php artisan key:generate && php artisan migrate:fresh --seed && php artisan serve --host 0.0.0.0"]

    mysql:
        image: mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            - "${DB_PORT}:${DB_PORT}"
        volumes:
            - mysql_data:/var/lib/mysql
    client:
        build:
            context: ./vue
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        volumes:
            - ./vue:/app
            - /app/node_modules

volumes:
    mysql_data:
