version: '3.8'
services:
    database:
        image: mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            - "${DB_PORT}:${DB_PORT}"
        volumes:
            - database_data:/var/lib/mysql

volumes:
    database_data:
